# ===============================
# Database Configuration
# ===============================
spring.application.name=library
spring.datasource.url=jdbc:postgresql://localhost:5432/library_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.web.resources.static-locations=file:/home/fahis/Desktop/Library/uploads/,classpath:/static/



# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# Server Configuration
# ===============================
server.port=8081
