#render db/final db

spring.application.name=veebipood
server.port=5000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d71qqufkijhs73crhfo0-a.oregon-postgres.render.com/veebipood_db
spring.datasource.username=user
spring.datasource.password=pvxNdHAWEsDf2mfeod7oGfrDrlVOpxH9