spring.application.name=movie_rental
server.port=5000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/movierental
spring.datasource.username=postgres
spring.datasource.password=1234